/*
Enter your query here.
*/
SELECT 
CASE 
    WHEN GRADE < 8 THEN "NULL"
    ELSE S.NAME
END, 
G.GRADE, S.MARKS
FROM STUDENTS S, GRADES G 
WHERE S.MARKS 
BETWEEN G.MIN_MARK AND G.MAX_MARK
ORDER BY GRADE DESC, S.NAME;